name: REACT CLI

on: 
  push:
    branches: 
      - "master"


jobs: 
 build:
    name: build-and-deploy
    runs-on: ubuntu-latest
    
    strategy:
       matrix:
         node-version: [15.x]
     
    steps: 
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm rebuild node-sass
    - run: npm run build 
    
    - name: Deploy app build to S3 bucket
      run: aws s3 sync ./dist/ s3://vinreactbasic --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: "dist"
      
