name: REACT CLI

on: 
  push:
    branches: 
      - "master"


jobs: 
 build:
    name: build-and-deploy
    runs-on: ubuntu-latest
    
    strategy:
       matrix:
         node-version: [15.x]
     
    steps: 
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
          
    - run: npm install
    - run: npm rebuild node-sass
    - run: npm run build 
    
    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync . s3://vinreactbasic
      
